### ISSUE TITLE
Images not displayed in uploaded/shared note

### ISSUE THREAD

**Issue by FiekeB** [Sekund/sekund-plugin-react#28] opened 2022-07-08 06:45 UTC
### Discussed in https://github.com/Sekund/sekund-plugin-react/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **FiekeB** July  8, 2022</sup>
Hi Candide, I have installed the Obsidian plugin for Sekund, created an account and  uploaded a small note with an image. But the image does not get published. I  tried with an image in my vault, and with an image I uploaded to Imgur. Both show fine in my vault, but not on Sekund. What can I do? 

My note looks like this:

```
Just a  quick testnote with an image to see if it gets through to Sekund.io alright. Let's use the logo I designed for Het 5e Element magazine! I am quite proud of this logo, and I think it's really goodlooking and cool. 

Bummer...the logo image does not get published somehow, even though it says on [this page](https://www.sekund.io/product/how-does-it-work) that it actually should be. 

![[Logo Het 5e Element.png]]

![Imgur](https://i.imgur.com/49r8ADp.png)
```

I can't understand why none of these two images show up at https://public.sekund.org/62c74f8859857f457c66975f/a-test-note-for-my-sekund-blog/ 

I did make sure, that I updated the uploaded note after changing it. I even deleted it and uploaded it again. 

</div>

**Comment by ckemmler** [comment] 2022-07-08 09:47
The issue is now fixed. We now store and refer to a notes assets without specifying the whole path to it., i.e an image at images/myfolder/someimage.png will be refered to as someimage.png and stored on S3 within a folder that is specific to that note. This however as a potentially harmful consequence. Because of the way Obsidian treats dependencies, a shared note that refers to a image that has the same name would use the existing image over the one that was newly downloaded... This needs more attention.

**Closed by ckemmler** 2022-07-08 09:47 UTC
